spring:

  config:
    activate:
      on-profile: development
    import: optional:secrets.yaml

  datasource:
    url: jdbc:mysql://localhost:3306/osable
    username: dev

eureka:
  client:
    service-url:
      defaultZone: http\://localhost:8761/eureka