spring:
  config:
    activate:
      on-profile: development, production

  application:
    name: gateway

  cloud:
    gateway:
      enabled: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081