spring:
  config:
    activate:
      on-profile: development

  data:
    redis:
      host: 127.0.0.1
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka