spring:
  config:
    activate:
      on-profile: production

eureka:
  client:
    service-url:
      defaultZone: http://discovery.osable.svc.cluster.local:8761/eureka
  instance:
    hostname: core.osable.svc.cluster.local

# env:
# spring.security.oauth2.client.registration.github.client-id
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID

# spring.security.oauth2.client.registration.github.client-secret
# SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET