name: Build Containers

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: true
          token: ${{ secrets.GH_PAT }}

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build discovery container
        run: ./gradlew :discovery:bootBuildImage --imageName=discovery:latest

      - name: Build gateway container
        run: ./gradlew :gateway:bootBuildImage --imageName=gateway:latest

      - name: Build core container
        run: ./gradlew :core:bootBuildImage --imageName=core:latest

      - name: Build url shortener container
        run: ./gradlew :url-shortener:bootBuildImage --imageName=url-shortener:latest

      - name: Push containers to Docker Registry
        run: |
          docker tag discovery:latest ${{ secrets.DOCKER_REGISTRY_URL }}/osable/discovery:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/osable/discovery:latest
          
          docker tag gateway:latest ${{ secrets.DOCKER_REGISTRY_URL }}/osable/gateway:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/osable/gateway:latest

          docker tag core:latest ${{ secrets.DOCKER_REGISTRY_URL }}/osable/core:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/osable/core:latest

          docker tag url-shortener:latest ${{ secrets.DOCKER_REGISTRY_URL }}/osable/url-shortener:latest
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/osable/url-shortener:latest
